
name: 'claim_to_fame'
version: '1.0.0'
config-version: 2


profile: 'dbt-learn'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

on-run-end: 
  - "{{ report_metrics() }}"


models:
  claim_to_fame:
    marts:
      +tags:
        - bi
      +schema: billing_analytics
      +materialized: table
    staging:
      +tags:
        - staging
      +schema: staging
    